#!/usr/bin/env ruby
$:.unshift File.join(File.dirname(__FILE__), "../lib")
require 'pry'
require 'zeevex_concurrency'
require 'zeevex_concurrency/deferred/delayed'
require 'zeevex_concurrency/deferred/future'
require 'zeevex_concurrency/deferred/promise'
require 'zeevex_concurrency/deferred/delay'

binding.pry
